#[test]
fn main_capability_grants_only_settings_models_and_bounded_audio_prototype_commands() {
    let capability: serde_json::Value =
        serde_json::from_str(include_str!("../capabilities/main.json"))
            .expect("main capability should contain valid JSON");

    assert_eq!(capability["windows"], serde_json::json!(["main"]));
    assert_eq!(
        capability["permissions"],
        serde_json::json!([
            "allow-get-settings",
            "allow-update-settings",
            "allow-choose-workspace",
            "allow-list-audio-devices",
            "allow-start-audio-capture-prototype",
            "allow-get-audio-capture-prototype-status",
            "allow-stop-audio-capture-prototype",
            "allow-list-transcription-models",
            "allow-download-transcription-model",
            "allow-cancel-model-download",
            "allow-resume-model-download",
            "allow-delete-transcription-model",
            "allow-set-default-transcription-model"
        ])
    );
    assert!(capability.get("remote").is_none());
    let serialized = capability.to_string();
    for forbidden in [
        "core:default",
        "dialog:",
        "fs:",
        "http:",
        "shell:",
        "process:",
    ] {
        assert!(!serialized.contains(forbidden));
    }
}

#[test]
fn tauri_configuration_enables_only_the_main_capability() {
    let configuration: serde_json::Value = serde_json::from_str(include_str!("../tauri.conf.json"))
        .expect("Tauri configuration should contain valid JSON");

    assert_eq!(
        configuration["app"]["security"]["capabilities"],
        serde_json::json!(["main"])
    );
}

#[test]
fn generated_app_permissions_map_only_the_expected_commands() {
    for (permission, identifier, command) in [
        (
            include_str!("../permissions/autogenerated/get_settings.toml"),
            "allow-get-settings",
            "get_settings",
        ),
        (
            include_str!("../permissions/autogenerated/update_settings.toml"),
            "allow-update-settings",
            "update_settings",
        ),
        (
            include_str!("../permissions/autogenerated/choose_workspace.toml"),
            "allow-choose-workspace",
            "choose_workspace",
        ),
        (
            include_str!("../permissions/autogenerated/list_audio_devices.toml"),
            "allow-list-audio-devices",
            "list_audio_devices",
        ),
        (
            include_str!("../permissions/autogenerated/start_audio_capture_prototype.toml"),
            "allow-start-audio-capture-prototype",
            "start_audio_capture_prototype",
        ),
        (
            include_str!("../permissions/autogenerated/get_audio_capture_prototype_status.toml"),
            "allow-get-audio-capture-prototype-status",
            "get_audio_capture_prototype_status",
        ),
        (
            include_str!("../permissions/autogenerated/stop_audio_capture_prototype.toml"),
            "allow-stop-audio-capture-prototype",
            "stop_audio_capture_prototype",
        ),
        (
            include_str!("../permissions/autogenerated/list_transcription_models.toml"),
            "allow-list-transcription-models",
            "list_transcription_models",
        ),
        (
            include_str!("../permissions/autogenerated/download_transcription_model.toml"),
            "allow-download-transcription-model",
            "download_transcription_model",
        ),
        (
            include_str!("../permissions/autogenerated/cancel_model_download.toml"),
            "allow-cancel-model-download",
            "cancel_model_download",
        ),
        (
            include_str!("../permissions/autogenerated/resume_model_download.toml"),
            "allow-resume-model-download",
            "resume_model_download",
        ),
        (
            include_str!("../permissions/autogenerated/delete_transcription_model.toml"),
            "allow-delete-transcription-model",
            "delete_transcription_model",
        ),
        (
            include_str!("../permissions/autogenerated/set_default_transcription_model.toml"),
            "allow-set-default-transcription-model",
            "set_default_transcription_model",
        ),
    ] {
        assert!(permission.contains(&format!("identifier = \"{identifier}\"")));
        assert!(permission.contains(&format!("commands.allow = [\"{command}\"]")));
        assert!(!permission.contains("remote"));
    }
}
