#[test]
fn main_capability_grants_only_the_read_only_settings_command() {
    let capability: serde_json::Value =
        serde_json::from_str(include_str!("../capabilities/main.json"))
            .expect("main capability should contain valid JSON");

    assert_eq!(capability["windows"], serde_json::json!(["main"]));
    assert_eq!(
        capability["permissions"],
        serde_json::json!(["allow-get-settings"])
    );
    assert!(capability.get("remote").is_none());
}

#[test]
fn tauri_configuration_enables_only_the_main_capability() {
    let configuration: serde_json::Value = serde_json::from_str(include_str!("../tauri.conf.json"))
        .expect("Tauri configuration should contain valid JSON");

    assert_eq!(
        configuration["app"]["security"]["capabilities"],
        serde_json::json!(["main"])
    );
}

#[test]
fn generated_app_permission_maps_only_get_settings() {
    let permission = include_str!("../permissions/autogenerated/get_settings.toml");

    assert!(permission.contains("identifier = \"allow-get-settings\""));
    assert!(permission.contains("commands.allow = [\"get_settings\"]"));
    assert!(!permission.contains("remote"));
}
