#[test]
fn main_capability_grants_only_the_three_settings_commands() {
    let capability: serde_json::Value =
        serde_json::from_str(include_str!("../capabilities/main.json"))
            .expect("main capability should contain valid JSON");

    assert_eq!(capability["windows"], serde_json::json!(["main"]));
    assert_eq!(
        capability["permissions"],
        serde_json::json!([
            "allow-get-settings",
            "allow-update-settings",
            "allow-choose-workspace"
        ])
    );
    assert!(capability.get("remote").is_none());
    let serialized = capability.to_string();
    for forbidden in [
        "core:default",
        "dialog:",
        "fs:",
        "http:",
        "shell:",
        "process:",
    ] {
        assert!(!serialized.contains(forbidden));
    }
}

#[test]
fn tauri_configuration_enables_only_the_main_capability() {
    let configuration: serde_json::Value = serde_json::from_str(include_str!("../tauri.conf.json"))
        .expect("Tauri configuration should contain valid JSON");

    assert_eq!(
        configuration["app"]["security"]["capabilities"],
        serde_json::json!(["main"])
    );
}

#[test]
fn generated_app_permissions_map_only_the_expected_commands() {
    for (permission, identifier, command) in [
        (
            include_str!("../permissions/autogenerated/get_settings.toml"),
            "allow-get-settings",
            "get_settings",
        ),
        (
            include_str!("../permissions/autogenerated/update_settings.toml"),
            "allow-update-settings",
            "update_settings",
        ),
        (
            include_str!("../permissions/autogenerated/choose_workspace.toml"),
            "allow-choose-workspace",
            "choose_workspace",
        ),
    ] {
        assert!(permission.contains(&format!("identifier = \"{identifier}\"")));
        assert!(permission.contains(&format!("commands.allow = [\"{command}\"]")));
        assert!(!permission.contains("remote"));
    }
}
